.TH docker4ssh 1 "December 13, 2021" docker4ssh "docker4ssh"

.SH NAME
docker4ssh - docker containers and more via ssh

.SH FILES
/etc/docker4ssh/docker4ssh.conf
    The configuration file. See \fIdocker4ssh.conf(5)\fR for more information

/etc/docker4ssh/profile/*
    Directory containing profiles. See \fIprofile.conf(5)\fR for more information

.SH SEE ALSO
docker4ssh.conf(5), profile.conf(5)

.SH BUGS
Discovered a bug? Well then it should get fixed as fast as possible. Feel free to open a new issue (https://github.com/ByteDream/crunchyroll-go/docker4ssh) or create a pull request (https://github.com/ByteDream/docker4ssh/pulls) on github.

.SH AUTHOR
Written by ByteDream (https://github.com/ByteDream)

.SH COPYRIGHT
Copyright (C) 2021 ByteDream

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
