version: '3'

services:
  docker4ssh:
    build: https://raw.githubusercontent.com/ByteDream/docker4ssh/main/examples/Dockerfile
    ports:
      - "2222:2222"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    container_name: docker4ssh
